[package]
name = "rust-stream-receive"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
rabbitmq-stream-client = "0.9.0"
tokio = { version = "1.47.1", features = ["rt", "rt-multi-thread", "macros"] }
